version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      # On définit les bases à créer via une variable personnalisée lue par notre script
      POSTGRES_MULTIPLE_DATABASES: product_db,pricing_db,inventory_db,customer_db,order_db
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"

  product-service:
    build: ./services/product_service
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://db_user:password@db:5432/product_db
  
  pricing-service:
    build: ./services/pricing_service
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://db_user:password@db:5432/pricing_db

  inventory-service:
    build: ./services/inventory_service
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://db_user:password@db:5432/inventory_db
  
  gateway-service:
    build: ./services/gateway_service
    ports: ["8000:8000"]

  customer-service:
    build: ./services/customer_service
    environment: [DATABASE_URL=postgresql://db_user:password@db:5432/customer_db]
    # Ports ZMQ: 5558 (REP pour Gateway), 5559 (PUB pour events)

  order-service:
    build: ./services/order_service
    environment: [DATABASE_URL=postgresql://db_user:password@db:5432/order_db]
    # Ports ZMQ: 5560 (REP pour Gateway), 5561 (PUB pour events)